base_url = "https://skeyll.github.io/SynicSugar/"
title = "SynicSugar"
theme = "EasyDocs"
compile_sass = true
build_search_index = true

DefaultContentLanguage = "en"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]

easydocs_heading_threshold = 5