base_url = "https://synicsugar.github.io/SynicSugar/"
title = "SynicSugar"
theme = "EasyDocs"
compile_sass = true
build_search_index = true

DefaultContentLanguage = "en"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
logo = "https://github.com/SynicSugar/SynicSugar/blob/main/Resources/Logo_doc.png?raw=true"
release = "https://api.github.com/repos/SynicSugar/SynicSugar/releases/latest"
favicon = "https://github.com/SynicSugar/SynicSugar/blob/main/Resources/favicon.ico?raw=true"
easydocs_heading_threshold = 5