base_url = "https://skeyll.github.io/SynicSugar/"
title = "SynicSugar"
theme = "EasyDocs"
compile_sass = true
build_search_index = true

DefaultContentLanguage = "en"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]

logo = "https://github.com/skeyll/SynicSugar/blob/main/Resources/Logo_doc.png"
favicon = "https://github.com/skeyll/SynicSugar/blob/main/Resources/favicon.ico"
easydocs_heading_threshold = 5