name: Get activation file
on: workflow_dispatch

jobs:
  activation:
    name: Request activation
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        id: license
        uses: game-ci/unity-request-activation-file@v2
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.license.outputs.filePath }}
          path: ${{ steps.license.outputs.filePath }}
