name: deploy_docs
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      
      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
