name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: false
        type: string
        default: 0.0.0
jobs:
  Build:
    name: Build .unitypacage with Unity.
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.20.f1
          buildMethod: SynicSugar.Build.BuildUnityPackage     
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: SynicSugar.${{ event.inputs.tag }}.unitypackage
          path: build

  CreateRelease:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           tag_name: ${{ event.inputs.tag }}
           release_name: v${{ event.inputs.tag }}
           
      - name: Download package
        uses: actions/download-artifact@v2
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: ./SynicSugar.${{ event.inputs.tag }}.unitypackage
           asset_name: SynicSugar.${{ event.inputs.tag }}.unitypackage
           asset_content_type: application/octet-stream
           path: build
           
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: SynciSugar.${{ env.GIT_TAG }}.unitypackage
          path: build
